#!/usr/bin/env bash
# fluxbench-calibrate.sh — calibrate FluxBench thresholds from ground-truth fixtures
# Usage: fluxbench-calibrate.sh --fixtures-dir <dir> --output <thresholds.yaml> [--mock]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Argument parsing ---
fixtures_dir=""
output_file=""
mock_mode=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --fixtures-dir) fixtures_dir="$2"; shift 2 ;;
    --output)       output_file="$2"; shift 2 ;;
    --mock)         mock_mode=true; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -n "$fixtures_dir" ]] || { echo "Error: --fixtures-dir required" >&2; exit 1; }
[[ -n "$output_file" ]]  || { echo "Error: --output required" >&2; exit 1; }
[[ -d "$fixtures_dir" ]] || { echo "Error: fixtures directory not found: $fixtures_dir" >&2; exit 1; }

if [[ "$mock_mode" != "true" ]]; then
  echo "Error: Real model invocation not yet supported. Use --mock for testing." >&2
  exit 1
fi

# --- Collect scores across all fixtures ---
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

# Metrics arrays — will be populated per-fixture
declare -a scores_format scores_recall scores_fp scores_severity scores_persona

fixture_count=0

for fixture_dir in "$fixtures_dir"/fixture-*/; do
  [[ -d "$fixture_dir" ]] || continue
  gt_file="${fixture_dir}/ground-truth.json"
  [[ -f "$gt_file" ]] || { echo "Warning: no ground-truth.json in $fixture_dir, skipping" >&2; continue; }

  fixture_id="$(basename "$fixture_dir")"
  run_id="calibrate-${fixture_id}-$(date -u +%s)"

  # In --mock mode: create qualification-output.json from ground-truth
  # The ground-truth IS the model output, so all scores should be perfect
  qual_output="${tmpdir}/${fixture_id}-qual-output.json"

  # Convert ground-truth to qualification output format
  python3 -c "
import json, sys

gt = json.load(open('${gt_file}'))

qual = {
    'metadata': {
        'qualification_run_id': '${run_id}',
        'fixture_id': gt.get('fixture_id', '${fixture_id}'),
        'source': 'calibration-mock'
    },
    'model_slug': 'calibration-mock',
    'format_compliance_rate': 1.0,
    'findings': gt.get('findings', [])
}

json.dump(qual, sys.stdout, indent=2)
" > "$qual_output"

  # Use the ground-truth as the baseline (bootstrapping: GT vs GT = perfect scores)
  result_file="${tmpdir}/${fixture_id}-result.json"

  # Run fluxbench-score.sh
  bash "${SCRIPT_DIR}/fluxbench-score.sh" "$qual_output" "$gt_file" "$result_file" 2>/dev/null || {
    echo "Warning: scoring failed for $fixture_id, skipping" >&2
    continue
  }

  # Extract metric values from the result
  fmt=$(jq -r '.metrics."fluxbench-format-compliance"' "$result_file")
  rec=$(jq -r '.metrics."fluxbench-finding-recall"' "$result_file")
  fp=$(jq -r '.metrics."fluxbench-false-positive-rate"' "$result_file")
  sev=$(jq -r '.metrics."fluxbench-severity-accuracy"' "$result_file")
  # persona-adherence is null in scoring — default to 1.0 for mock calibration
  per=$(jq -r '.metrics."fluxbench-persona-adherence" // 1.0' "$result_file")
  [[ "$per" == "null" ]] && per="1.0"

  scores_format+=("$fmt")
  scores_recall+=("$rec")
  scores_fp+=("$fp")
  scores_severity+=("$sev")
  scores_persona+=("$per")

  fixture_count=$((fixture_count + 1))
  echo "Calibrated: $fixture_id (recall=$rec fp=$fp severity=$sev format=$fmt)" >&2
done

if [[ "$fixture_count" -eq 0 ]]; then
  echo "Error: no fixtures found in $fixtures_dir" >&2
  exit 1
fi

echo "Processed $fixture_count fixtures" >&2

# --- Compute p25 thresholds ---
# p25 = 25th percentile (conservative — achievable by 75% of runs)
# For false-positive-rate: higher_is_worse, so use p75 instead (75th percentile = the worst 25%)
compute_percentile() {
  local percentile="$1"
  shift
  local -a values=("$@")
  python3 -c "
import sys
percentile = float(sys.argv[1])
values = sorted([float(v) for v in sys.argv[2:]])
n = len(values)
if n == 0:
    print(0.0)
elif n == 1:
    print(values[0])
else:
    p = percentile / 100.0
    idx = p * (n - 1)
    lo = int(idx)
    hi = min(lo + 1, n - 1)
    frac = idx - lo
    result = values[lo] + frac * (values[hi] - values[lo])
    print(round(result, 4))
" "$percentile" "${values[@]}"
}

t_format=$(compute_percentile 25 "${scores_format[@]}")
t_recall=$(compute_percentile 25 "${scores_recall[@]}")
# For FP rate, use p75 (higher = worse, so p75 is the conservative upper bound)
t_fp=$(compute_percentile 75 "${scores_fp[@]}")
t_severity=$(compute_percentile 25 "${scores_severity[@]}")
t_persona=$(compute_percentile 25 "${scores_persona[@]}")

calibrated_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# --- Write output thresholds YAML ---
mkdir -p "$(dirname "$output_file")"

cat > "$output_file" <<YAML
# FluxBench Thresholds — calibrated from ${fixture_count} fixtures
# Generated by: fluxbench-calibrate.sh --mock
# Calibration date: ${calibrated_at}
version: 1
source: calibrated
calibrated_at: "${calibrated_at}"
fixture_count: ${fixture_count}

thresholds:
  fluxbench-format-compliance: ${t_format}
  fluxbench-finding-recall: ${t_recall}
  fluxbench-false-positive-rate: ${t_fp}
  fluxbench-severity-accuracy: ${t_severity}
  fluxbench-persona-adherence: ${t_persona}
YAML

echo "Thresholds written to $output_file (source: calibrated, fixtures: $fixture_count)" >&2
