#!/usr/bin/env python3
"""
agent-roles.yaml ↔ subagent frontmatter drift audit.

agent-roles.yaml is the host-agnostic policy source of truth. Each
host (Claude Code, Codex, Hermes, Droid) projects it into its own
config format. Claude Code's projection is the `model:` field in each
subagent .md frontmatter.

This script walks first-party plugin agent definitions and reports
where frontmatter ≠ yaml. Reports states per agent:
  AGREE              frontmatter model is within yaml [min,max] band
  AGREE_OFF_DEFAULT  within band, off the declared default tier
  BELOW              frontmatter sits below yaml min_model (floor violation)
  ABOVE              frontmatter sits above yaml max_model (ceiling violation)
  UNMAPPED           agent has frontmatter but no yaml role entry
  NO_MODEL           frontmatter omits `model:` and agent is not in host-default

Modes:
  default            exit 0 always (diagnostic for ad-hoc runs)
  --strict           exit 1 if any drift state appears (BELOW, ABOVE,
                     UNMAPPED, NO_MODEL); used by CI

Operating modes (auto-detected from --root, can be overridden):

  Monorepo mode      --root points at the Sylveste monorepo root.
                     Roles yaml resolved at interverse/interflux/config/...;
                     all first-party agent dirs (Clavain, intersynth, etc.)
                     are walked. Used for ad-hoc whole-ecosystem audits.

  Subrepo mode       --root points at the interflux subrepo root (CI default).
                     Roles yaml resolved at config/flux-drive/agent-roles.yaml;
                     only `agents/` is walked. Sibling subrepos audit their
                     own agents with their own copies of this script + a
                     copy of agent-roles.yaml in CI. UNMAPPED in this mode
                     is expected for agents owned by other subrepos and
                     SHOULD be filtered with --only-agents-in-dirs (default
                     when --agent-dir is supplied).

Origin: Sylveste-0zy (audit) + Sylveste-onp (CI gate). Replaces the
pre-promotion gitignored copy under docs/research/microrouter-phase1/.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

# Repo root resolves from this script's location:
#   <root>/interverse/interflux/scripts/verify_frontmatter.py
#   parents:  [0]=scripts, [1]=interflux, [2]=interverse, [3]=<root>
DEFAULT_ROOT = Path(__file__).resolve().parents[3]

# Default agent dirs for monorepo mode — first-party only. Excludes
# ~/.claude/agents (generated by interflux flux-agent) and
# docs-sp-reference (historical archive).
DEFAULT_AGENT_DIRS_MONOREPO = [
    "os/Clavain/agents",
    "interverse/interflux/agents",
    "interverse/intersynth/agents",
    "interverse/interfluence/agents",
    "interverse/interdeep/agents",
    "interverse/intercraft/agents",
    "interverse/intertrace/agents",
    "interverse/interlock/agents",
    "apps/Autarch/agents",
]

# Candidate yaml locations: monorepo first, subrepo second.
ROLES_YAML_CANDIDATES = [
    "interverse/interflux/config/flux-drive/agent-roles.yaml",
    "config/flux-drive/agent-roles.yaml",
]

TIER_ORDER = {"haiku": 0, "sonnet": 1, "opus": 2}

# States that count as drift in --strict mode.
DRIFT_STATES = {"BELOW", "ABOVE", "UNMAPPED", "NO_MODEL"}


def parse_frontmatter(path: Path) -> dict:
    """Read YAML frontmatter from a `.md` file (between first two `---` markers)."""
    text = path.read_text()
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    try:
        return yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        return {}


def load_roles(roles_yaml: Path) -> dict:
    """Load agent-roles.yaml → {agent_name: role_dict}."""
    doc = yaml.safe_load(roles_yaml.read_text())
    roles = doc["roles"]
    mapping = {}
    for role_name, role_def in roles.items():
        if role_def is None:
            continue
        for a in role_def.get("agents") or []:
            mapping[a] = {
                "role": role_name,
                "model_tier": role_def.get("model_tier"),
                "min_model": role_def.get("min_model"),
                "max_model": role_def.get("max_model"),
            }
    return mapping


def normalize_model(m):
    """Strip 'claude-*-' wrappers; return one of haiku/sonnet/opus or None."""
    if not m:
        return None
    m = str(m).lower()
    for k in TIER_ORDER:
        if k in m:
            return k
    return None


def classify(fm_model: str | None, role: dict) -> str:
    """Compare frontmatter model against yaml role band."""
    # host-default role explicitly declares "no model opinion" — NO_MODEL is the intent.
    if not fm_model:
        if role.get("role") == "host-default":
            return "AGREE"
        return "NO_MODEL"
    fm_tier = TIER_ORDER[fm_model]
    min_m = role.get("min_model")
    max_m = role.get("max_model")
    tier_default = role.get("model_tier")

    if min_m and fm_tier < TIER_ORDER[min_m]:
        return "BELOW"
    if max_m and fm_tier > TIER_ORDER[max_m]:
        return "ABOVE"
    if tier_default and fm_model != tier_default:
        return "AGREE_OFF_DEFAULT"
    return "AGREE"


def resolve_roles_yaml(root: Path, override: Path | None) -> Path:
    """Find agent-roles.yaml under root; honor explicit override."""
    if override is not None:
        p = override if override.is_absolute() else (root / override)
        if not p.exists():
            print(f"FATAL: --roles-yaml {p} not found", file=sys.stderr)
            sys.exit(2)
        return p
    for rel in ROLES_YAML_CANDIDATES:
        p = root / rel
        if p.exists():
            return p
    print(
        "FATAL: agent-roles.yaml not found at any of "
        + ", ".join(ROLES_YAML_CANDIDATES),
        file=sys.stderr,
    )
    sys.exit(2)


def scan(
    root: Path,
    agent_dirs: list[str],
    roles_yaml_override: Path | None = None,
) -> list[dict]:
    roles_yaml = resolve_roles_yaml(root, roles_yaml_override)
    role_map = load_roles(roles_yaml)

    results: list[dict] = []
    seen_paths: set[Path] = set()
    for rel in agent_dirs:
        d = Path(rel) if Path(rel).is_absolute() else (root / rel)
        if not d.exists():
            continue
        for p in d.rglob("*.md"):
            if p in seen_paths:
                continue
            seen_paths.add(p)
            fm = parse_frontmatter(p)
            name = fm.get("name") or p.stem
            fm_model = normalize_model(fm.get("model"))
            # Skip files that aren't subagent definitions (no name, no model)
            if not fm.get("name") and not fm.get("model"):
                continue

            role = role_map.get(name)
            if role is None:
                bare = name.split(":", 1)[-1] if ":" in name else name
                role = role_map.get(bare)

            if role is None:
                state = "UNMAPPED"
                role_name = ""
                min_m = ""
                max_m = ""
                tier_default = ""
            else:
                state = classify(fm_model, role)
                role_name = role["role"]
                min_m = role.get("min_model") or ""
                max_m = role.get("max_model") or ""
                tier_default = role.get("model_tier") or ""

            results.append(
                {
                    "agent": name,
                    "path": str(p.relative_to(root)),
                    "fm_model": fm_model or "",
                    "role": role_name,
                    "min_model": min_m,
                    "max_model": max_m,
                    "tier_default": tier_default,
                    "state": state,
                }
            )

    state_order = {
        "BELOW": 0,
        "ABOVE": 1,
        "UNMAPPED": 2,
        "NO_MODEL": 3,
        "AGREE_OFF_DEFAULT": 4,
        "AGREE": 5,
    }
    results.sort(key=lambda r: (state_order.get(r["state"], 9), r["role"], r["agent"]))
    return results


def emit_table(results: list[dict]) -> None:
    print("state\tagent\trole\tfm_model\ttier_default\tmin_model\tmax_model\tpath")
    for r in results:
        print(
            "\t".join(
                [
                    r["state"],
                    r["agent"],
                    r["role"],
                    r["fm_model"],
                    r["tier_default"],
                    r["min_model"],
                    r["max_model"],
                    r["path"],
                ]
            )
        )


def emit_summary(results: list[dict], stream=sys.stderr) -> Counter:
    states = Counter(r["state"] for r in results)
    print("", file=stream)
    print("=== Summary ===", file=stream)
    print(f"Agents scanned: {len(results)}", file=stream)
    for s in ["BELOW", "ABOVE", "UNMAPPED", "NO_MODEL", "AGREE_OFF_DEFAULT", "AGREE"]:
        n = states.get(s, 0)
        if n:
            print(f"  {s:<20} {n}", file=stream)

    print("", file=stream)
    print("=== Per-role drift ===", file=stream)
    by_role = defaultdict(Counter)
    for r in results:
        if r["role"]:
            by_role[r["role"]][r["state"]] += 1
    for role in sorted(by_role):
        counts = dict(by_role[role])
        total = sum(counts.values())
        n_agree = counts.get("AGREE", 0) + counts.get("AGREE_OFF_DEFAULT", 0)
        print(
            f"  {role:<28} n={total:<3} agree={n_agree}  drift={total - n_agree}  {counts}",
            file=stream,
        )
    return states


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--root",
        type=Path,
        default=DEFAULT_ROOT,
        help="Repo root (default: resolved from script location)",
    )
    ap.add_argument(
        "--roles-yaml",
        type=Path,
        default=None,
        help=(
            "Path to agent-roles.yaml (default: auto-detect under --root at "
            "interverse/interflux/config/... or config/...)"
        ),
    )
    ap.add_argument(
        "--agent-dir",
        action="append",
        default=None,
        metavar="DIR",
        help=(
            "Agent directory to scan (repeatable). If supplied, replaces the "
            "default cross-subrepo list. Use 'agents' for subrepo-scoped CI."
        ),
    )
    ap.add_argument(
        "--strict",
        action="store_true",
        help="Exit 1 if any drift state appears (BELOW, ABOVE, UNMAPPED, NO_MODEL)",
    )
    ap.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress TSV table; print summary only",
    )
    args = ap.parse_args()

    agent_dirs = args.agent_dir if args.agent_dir else DEFAULT_AGENT_DIRS_MONOREPO
    results = scan(args.root, agent_dirs, args.roles_yaml)
    if not args.quiet:
        emit_table(results)
    states = emit_summary(results)

    if args.strict:
        drift = sum(states.get(s, 0) for s in DRIFT_STATES)
        if drift > 0:
            offenders = ", ".join(
                f"{s}={states[s]}" for s in DRIFT_STATES if states.get(s)
            )
            print(f"\nSTRICT: drift detected ({offenders}) — failing", file=sys.stderr)
            return 1
        print("\nSTRICT: no drift — OK", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
